### ISSUE TITLE
Is SpMM not supported in this version?

### ISSUE THREAD

**Issue by reikdas** [sparse-specialize/partially-strided-codelet#2]
If I try to execute an SpMM over a matrix, I run into this error https://github.com/sparse-specialize/partially-strided-codelet/blob/master/src/DDT.cpp#L201 because it seems like the SPMM flag has not been handled?

**Comment by cheshmi** [comment]
I think you should be fine if you use the `spmm_demo`. In this demo, the `SPMM` option should be defined:
https://github.com/sparse-specialize/partially-strided-codelet/blob/c03d0593411c8afc9c6861de152695c453358a04/src/Input.cpp#L106

Here is where the demo is:
https://github.com/sparse-specialize/partially-strided-codelet/blob/c03d0593411c8afc9c6861de152695c453358a04/demo/SPMM_demo.cpp
As far as I remember, we used SpMV codelets for SpMM as well. @cetiniz please comment if I miss something.

**Comment by reikdas** [comment]
Thanks!
